name: Nightly
on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:
jobs:
  publish_nightly:
    uses: yiannistri/highlander-reusable-workflows/.github/workflows/operator-with-latest-rancher-build.yaml@update-dockerfile
    with:
      operator_name: aks-operator
      operator_commit: ${{ github.sha }}
